/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;

/**
 *
 * @author nolas
 */
public class VtnMP extends javax.swing.JFrame
{

    /**
     * Creates new form VtnMA
     */
    public VtnMP()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        modificacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        clave = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox<>();
        desnutricion = new javax.swing.JComboBox<>();
        sobrepeso = new javax.swing.JComboBox<>();
        alergias = new javax.swing.JComboBox<>();
        obesidad = new javax.swing.JComboBox<>();
        diabetes = new javax.swing.JComboBox<>();
        otros = new javax.swing.JTextField();
        estatus = new javax.swing.JComboBox<>();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(480, 670));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 670));

        modificacion.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        modificacion.setText("MODIFICACION DE PERSONAL");

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel2.setText("Clave:");

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel3.setText("Sexo:");

        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel4.setText("Desnutrición:");

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel5.setText("Sobrepeso:");

        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel6.setText("Alergias:");

        jLabel7.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel7.setText("Obesidad:");

        jLabel8.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel8.setText("Diabetes:");

        jLabel9.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel9.setText("Otros :");

        jLabel10.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel10.setText("Estatus");

        clave.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                claveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                claveKeyTyped(evt);
            }
        });

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "Masculino", "Femenino" }));
        sexo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                sexoItemStateChanged(evt);
            }
        });

        desnutricion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        desnutricion.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                desnutricionItemStateChanged(evt);
            }
        });

        sobrepeso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        sobrepeso.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                sobrepesoItemStateChanged(evt);
            }
        });

        alergias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        alergias.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                alergiasItemStateChanged(evt);
            }
        });

        obesidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        obesidad.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                obesidadItemStateChanged(evt);
            }
        });

        diabetes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        diabetes.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                diabetesItemStateChanged(evt);
            }
        });

        otros.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                otrosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                otrosKeyTyped(evt);
            }
        });

        estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "Base", "Temporal" }));
        estatus.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                estatusItemStateChanged(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modificacion)
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aceptar)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(desnutricion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sobrepeso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(alergias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(obesidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(diabetes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(otros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cancelar))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(modificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(desnutricion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sobrepeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(alergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(obesidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(diabetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(otros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_claveKeyTyped
    {//GEN-HEADEREND:event_claveKeyTyped
        Validaciones.validaAlfanumerico(evt, 9, clave.getText());
    }//GEN-LAST:event_claveKeyTyped

    private void claveKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_claveKeyPressed
    {//GEN-HEADEREND:event_claveKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (ManipulacionProyecto.buscarCve(VtnPrincipal.arrDatos, clave.getText()) == -1)
            {
                Mensajes.error(this, "La clave no se encuentra registrada");
                cancelarActionPerformed(null);

            }

        }
        Validaciones.enterCadenaNoVacia(this, evt, clave, sexo);
    }//GEN-LAST:event_claveKeyPressed

    private void sexoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_sexoItemStateChanged
    {//GEN-HEADEREND:event_sexoItemStateChanged
        CtrlInterfaz.cambia(desnutricion);
    }//GEN-LAST:event_sexoItemStateChanged

    private void desnutricionItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_desnutricionItemStateChanged
    {//GEN-HEADEREND:event_desnutricionItemStateChanged
        CtrlInterfaz.cambia(sobrepeso);
    }//GEN-LAST:event_desnutricionItemStateChanged

    private void sobrepesoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_sobrepesoItemStateChanged
    {//GEN-HEADEREND:event_sobrepesoItemStateChanged
        CtrlInterfaz.cambia(alergias);
    }//GEN-LAST:event_sobrepesoItemStateChanged

    private void alergiasItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_alergiasItemStateChanged
    {//GEN-HEADEREND:event_alergiasItemStateChanged
        CtrlInterfaz.cambia(obesidad);
    }//GEN-LAST:event_alergiasItemStateChanged

    private void obesidadItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_obesidadItemStateChanged
    {//GEN-HEADEREND:event_obesidadItemStateChanged
        CtrlInterfaz.cambia(diabetes);
    }//GEN-LAST:event_obesidadItemStateChanged

    private void diabetesItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_diabetesItemStateChanged
    {//GEN-HEADEREND:event_diabetesItemStateChanged
        CtrlInterfaz.cambia(otros);
    }//GEN-LAST:event_diabetesItemStateChanged

    private void otrosKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrosKeyTyped
    {//GEN-HEADEREND:event_otrosKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, otros.getText());
    }//GEN-LAST:event_otrosKeyTyped

    private void otrosKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrosKeyPressed
    {//GEN-HEADEREND:event_otrosKeyPressed
        if (!otros.getText().equals(""))
        {
            Validaciones.enter(this, evt, estatus, otros);
            Validaciones.enterCadenaNoVacia(this, evt, otros, estatus);
        } else
        {
            Validaciones.enter(this, evt, otros, otros);
            Validaciones.enterCadenaNoVacia(this, evt, otros, otros);

        }
    }//GEN-LAST:event_otrosKeyPressed

    private void estatusItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_estatusItemStateChanged
    {//GEN-HEADEREND:event_estatusItemStateChanged
        CtrlInterfaz.cambia(aceptar);
    }//GEN-LAST:event_estatusItemStateChanged

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        int pos;
        otros.setText(otros.getText().toUpperCase());
        try
        {

            if (ManipulacionProyecto.buscarCve(VtnPrincipal.arrDatos, clave.getText()) != -1)
            {

                if (sexo.getSelectedIndex() == 0 || desnutricion.getSelectedIndex() == 0 || sobrepeso.getSelectedIndex() == 0 || alergias.getSelectedIndex() == 0 || obesidad.getSelectedIndex() == 0 || diabetes.getSelectedIndex() == 0 || estatus.getSelectedIndex() == 0)
                {
                    Mensajes.error(this, "Porfavor, selecciona una opcion");

                } else
                {
                    if (clave.getText().equals("") || otros.getText().equals(""))
                    {
                        Mensajes.error(this, "La caja de texto esta vacia");
                    } else
                    {
                        pos = ManipulacionProyecto.buscarCve(VtnPrincipal.arrDatos, clave.getText());
                        VtnPrincipal.arrDatos = ManipulacionProyecto.modificarPersonal(VtnPrincipal.arrDatos, pos, clave.getText(), sexo.getSelectedIndex(), desnutricion.getSelectedIndex(), sobrepeso.getSelectedIndex(), alergias.getSelectedIndex(), obesidad.getSelectedIndex(), diabetes.getSelectedIndex(), otros.getText(), estatus.getSelectedIndex());
                        Mensajes.exito(this, "Datos modificados correctamente");
                        resetCombos();
                        cancelarActionPerformed(evt);
                    }

                }
            } else
            {
                Mensajes.error(this, "La clave no se encuentra registrada");
                cancelarActionPerformed(evt);
            }

        } catch (Exception e)
        {
            Mensajes.error(this, "Error..." + e.toString());
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarActionPerformed
    {//GEN-HEADEREND:event_cancelarActionPerformed
        CtrlInterfaz.limpia(clave, sexo, desnutricion, obesidad, otros, estatus);
        CtrlInterfaz.habilita(false, sexo, desnutricion, obesidad, otros, estatus, aceptar);
        CtrlInterfaz.cambia(clave);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnMP().setVisible(true);
            }
        });
    }

    private void resetCombos()
    {
        sexo.setSelectedIndex(0);
        desnutricion.setSelectedIndex(0);
        sobrepeso.setSelectedIndex(0);
        alergias.setSelectedIndex(0);
        obesidad.setSelectedIndex(0);
        diabetes.setSelectedIndex(0);
        estatus.setSelectedIndex(0);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JComboBox<String> alergias;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField clave;
    private javax.swing.JComboBox<String> desnutricion;
    private javax.swing.JComboBox<String> diabetes;
    private javax.swing.JComboBox<String> estatus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modificacion;
    private javax.swing.JComboBox<String> obesidad;
    private javax.swing.JTextField otros;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JComboBox<String> sobrepeso;
    // End of variables declaration//GEN-END:variables
}
