/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;

/**
 *
 * @author nolas
 */
public class VtnRA extends javax.swing.JFrame
{

    /**
     * Creates new form VtnRA
     */
    public VtnRA()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        clave = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        apP = new javax.swing.JTextField();
        apM = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox<>();
        desnutricion = new javax.swing.JComboBox<>();
        sobrepeso = new javax.swing.JComboBox<>();
        alergias = new javax.swing.JComboBox<>();
        obesidad = new javax.swing.JComboBox<>();
        diabetes = new javax.swing.JComboBox<>();
        viveCon = new javax.swing.JComboBox<>();
        carrera = new javax.swing.JComboBox<>();
        otros = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(480, 670));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 670));

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE ALUMNOS");

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel2.setText("Clave:");

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel4.setText("Apellido Paterno:");

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel5.setText("Apellido Materno:");

        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel6.setText("Sexo:");

        jLabel7.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel7.setText("Desnutricion:");

        jLabel8.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel8.setText("Sobrepeso:");

        jLabel9.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel9.setText("Alergias:");

        jLabel10.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel10.setText("Obesidad:");

        jLabel11.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel11.setText("Diabetes:");

        jLabel12.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel12.setText("Otros:");

        jLabel13.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel13.setText("Vive con:");

        jLabel14.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel14.setText("Carrera: ");

        clave.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                claveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                claveKeyTyped(evt);
            }
        });

        nom.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomKeyTyped(evt);
            }
        });

        apP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                apPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                apPKeyTyped(evt);
            }
        });

        apM.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                apMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                apMKeyTyped(evt);
            }
        });

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "Masculino", "Femenino" }));
        sexo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                sexoItemStateChanged(evt);
            }
        });

        desnutricion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        desnutricion.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                desnutricionItemStateChanged(evt);
            }
        });

        sobrepeso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        sobrepeso.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                sobrepesoItemStateChanged(evt);
            }
        });

        alergias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        alergias.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                alergiasItemStateChanged(evt);
            }
        });

        obesidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        obesidad.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                obesidadItemStateChanged(evt);
            }
        });

        diabetes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        diabetes.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                diabetesItemStateChanged(evt);
            }
        });

        viveCon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "Mama y Papa", "Solo Mama", "Solo Papa", "Otros" }));
        viveCon.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                viveConItemStateChanged(evt);
            }
        });

        carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "Ingenieria Electromecanica", "Ingenieria Electronica", "Ingenieria en Gestion Empresarial", "Ingenieria Industrial", "Ingenieria Logistica", "Ingenieria Mecatronica", "Ingenieria Química", "Ingenieria en Sistemas Computacionales", "Ingenieria en TIC'S" }));
        carrera.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                carreraItemStateChanged(evt);
            }
        });

        otros.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                otrosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                otrosKeyTyped(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(aceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(apP, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(apM, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(desnutricion, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sobrepeso, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(alergias, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(obesidad, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(diabetes, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(otros, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viveCon, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cancelar))
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(apP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(apM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(desnutricion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sobrepeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(alergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(obesidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(diabetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(otros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(viveCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_claveKeyTyped
    {//GEN-HEADEREND:event_claveKeyTyped
        Validaciones.validaAlfanumerico(evt, 9, clave.getText());
    }//GEN-LAST:event_claveKeyTyped

    private void claveKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_claveKeyPressed
    {//GEN-HEADEREND:event_claveKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (ManipulacionProyecto.buscarCve(VtnPrincipal.arrDatos, clave.getText()) != -1)
            {
                Mensajes.error(this, "La clave ya se encuentra registrada");
                cancelarActionPerformed(null);
            }

        }
        Validaciones.enterCadenaNoVacia(this, evt, clave, nom);
    }//GEN-LAST:event_claveKeyPressed

    private void nomKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyTyped
    {//GEN-HEADEREND:event_nomKeyTyped
        Validaciones.validaAlfabeticos(evt, 15, nom.getText());
    }//GEN-LAST:event_nomKeyTyped

    private void nomKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyPressed
    {//GEN-HEADEREND:event_nomKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, nom, apP);
    }//GEN-LAST:event_nomKeyPressed

    private void apPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apPKeyTyped
    {//GEN-HEADEREND:event_apPKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, apP.getText());
    }//GEN-LAST:event_apPKeyTyped

    private void apPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apPKeyPressed
    {//GEN-HEADEREND:event_apPKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, apP, apM);
    }//GEN-LAST:event_apPKeyPressed

    private void apMKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apMKeyTyped
    {//GEN-HEADEREND:event_apMKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, apM.getText());
    }//GEN-LAST:event_apMKeyTyped

    private void apMKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apMKeyPressed
    {//GEN-HEADEREND:event_apMKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, apM, sexo);
    }//GEN-LAST:event_apMKeyPressed

    private void sexoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_sexoItemStateChanged
    {//GEN-HEADEREND:event_sexoItemStateChanged
        CtrlInterfaz.cambia(desnutricion);
    }//GEN-LAST:event_sexoItemStateChanged

    private void desnutricionItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_desnutricionItemStateChanged
    {//GEN-HEADEREND:event_desnutricionItemStateChanged
        CtrlInterfaz.cambia(sobrepeso);
    }//GEN-LAST:event_desnutricionItemStateChanged

    private void sobrepesoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_sobrepesoItemStateChanged
    {//GEN-HEADEREND:event_sobrepesoItemStateChanged
        CtrlInterfaz.cambia(alergias);
    }//GEN-LAST:event_sobrepesoItemStateChanged

    private void alergiasItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_alergiasItemStateChanged
    {//GEN-HEADEREND:event_alergiasItemStateChanged
        CtrlInterfaz.cambia(obesidad);
    }//GEN-LAST:event_alergiasItemStateChanged

    private void obesidadItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_obesidadItemStateChanged
    {//GEN-HEADEREND:event_obesidadItemStateChanged
        CtrlInterfaz.cambia(diabetes);
    }//GEN-LAST:event_obesidadItemStateChanged

    private void diabetesItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_diabetesItemStateChanged
    {//GEN-HEADEREND:event_diabetesItemStateChanged
        CtrlInterfaz.cambia(otros);
    }//GEN-LAST:event_diabetesItemStateChanged

    private void otrosKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrosKeyTyped
    {//GEN-HEADEREND:event_otrosKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, otros.getText());
    }//GEN-LAST:event_otrosKeyTyped

    private void otrosKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrosKeyPressed
    {//GEN-HEADEREND:event_otrosKeyPressed
        if (!otros.getText().equals(""))
        {
            Validaciones.enter(this, evt, viveCon, otros);
            Validaciones.enterCadenaNoVacia(this, evt, otros, viveCon);
        } else
        {
            Validaciones.enter(this, evt, otros, otros);
            Validaciones.enterCadenaNoVacia(this, evt, otros, otros);
        
        }
    }//GEN-LAST:event_otrosKeyPressed

    private void viveConItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_viveConItemStateChanged
    {//GEN-HEADEREND:event_viveConItemStateChanged
        CtrlInterfaz.cambia(carrera);
    }//GEN-LAST:event_viveConItemStateChanged

    private void carreraItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_carreraItemStateChanged
    {//GEN-HEADEREND:event_carreraItemStateChanged
        CtrlInterfaz.cambia(aceptar);
    }//GEN-LAST:event_carreraItemStateChanged

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        otros.setText(otros.getText().toUpperCase());
        try
        {

            if (ManipulacionProyecto.buscarCve(VtnPrincipal.arrDatos, clave.getText()) == -1)
            {

                if (sexo.getSelectedIndex() == 0 || desnutricion.getSelectedIndex() == 0 || sobrepeso.getSelectedIndex() == 0 || alergias.getSelectedIndex() == 0 || obesidad.getSelectedIndex() == 0 || diabetes.getSelectedIndex() == 0 || viveCon.getSelectedIndex() == 0 || carrera.getSelectedIndex() == 0)
                {
                    Mensajes.error(this, "Porfavor, selecciona una opcion");

                } else
                {
                    if (clave.getText().equals("") || nom.getText().equals("") || apP.getText().equals("") || apM.getText().equals("") || otros.getText().equals(""))
                    {
                        Mensajes.error(this, "La caja de texto esta vacia");
                    } else
                    {
                        VtnPrincipal.arrDatos = ManipulacionProyecto.agregarAlumno(VtnPrincipal.arrDatos, 1, true, asignarDatos(null, viveCon.getSelectedIndex(), carrera.getSelectedIndex(), clave.getText(), nom.getText(), apP.getText(), apM.getText(), sexo.getSelectedIndex(), desnutricion.getSelectedIndex(), sobrepeso.getSelectedIndex(), alergias.getSelectedIndex(), obesidad.getSelectedIndex(), diabetes.getSelectedIndex(), otros.getText()));
                        VtnPrincipal.matH = ManipulacionProyecto.agregarfila(VtnPrincipal.matH);
                        Mensajes.exito(this, "Datos registrados correctamente");
                        resetCombos();
                        cancelarActionPerformed(evt);

                    }

                }
            } else
            {
                Mensajes.error(this, "La clave ya se encuentra registrada");
                cancelarActionPerformed(evt);
            }

        } catch (Exception e)
        {
            Mensajes.error(this, "Error..." + e.toString());
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarActionPerformed
    {//GEN-HEADEREND:event_cancelarActionPerformed
        CtrlInterfaz.limpia(clave, nom, apP, apM, otros);
        CtrlInterfaz.habilita(false, nom, apP, apM, otros, sexo, desnutricion, sobrepeso, alergias, obesidad, diabetes, otros, viveCon, carrera, aceptar);
        CtrlInterfaz.cambia(clave);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnRA().setVisible(true);
            }
        });
    }

    private void resetCombos()
    {
        sexo.setSelectedIndex(0);
        desnutricion.setSelectedIndex(0);
        sobrepeso.setSelectedIndex(0);
        alergias.setSelectedIndex(0);
        obesidad.setSelectedIndex(0);
        diabetes.setSelectedIndex(0);
        viveCon.setSelectedIndex(0);
        carrera.setSelectedIndex(0);

    }

    private Alumnos asignarDatos(java.awt.event.ActionEvent evt, int viveCon, int carrera, String clave, String nombre, String apP, String apM, int sex, int des, int sobre, int aler, int obes, int diab, String otros)
    {
        char sexo = ' ';
        boolean desnutricion = false;
        boolean sobrepeso = false;
        boolean alergias = false;
        boolean obesidad = false;
        boolean diabetes = false;

        switch (sex)
        {
            case 1:
                sexo = 'M';
                break;
            case 2:
                sexo = 'F';
                break;
        }

        switch (des)
        {
            case 2:
                desnutricion = false;
                break;
            case 3:
                desnutricion = true;
                break;
        }
        switch (sobre)
        {
            case 2:
                sobrepeso = false;
                break;
            case 3:
                sobrepeso = true;
                break;
        }
        switch (aler)
        {
            case 2:
                alergias = false;
                break;
            case 3:
                alergias = true;
                break;
        }
        switch (obes)
        {
            case 2:
                obesidad = false;
                break;
            case 3:
                obesidad = true;
                break;
        }
        switch (diab)
        {
            case 2:
                diabetes = false;
                break;
            case 3:
                diabetes = true;
                break;
        }
        Alumnos obj = new Alumnos(viveCon, carrera, clave, nombre, apP, apM, sexo, desnutricion, sobrepeso, alergias, obesidad, diabetes, otros);
        return obj;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JComboBox<String> alergias;
    private javax.swing.JTextField apM;
    private javax.swing.JTextField apP;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox<String> carrera;
    private javax.swing.JTextField clave;
    private javax.swing.JComboBox<String> desnutricion;
    private javax.swing.JComboBox<String> diabetes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nom;
    private javax.swing.JComboBox<String> obesidad;
    private javax.swing.JTextField otros;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JComboBox<String> sobrepeso;
    private javax.swing.JComboBox<String> viveCon;
    // End of variables declaration//GEN-END:variables
}
