/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vtnsExtras;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import ventanaprincipal.VtnPrincipal;
import poo.Alumnos;
import poo.ManipulacionProyecto;
/**
 *
 * @author nolas
 */
public class VtnMP extends javax.swing.JFrame
{

    /**
     * Creates new form VtnMA
     */
    public VtnMP()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        modificacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        clave = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox<>();
        desnutricion = new javax.swing.JComboBox<>();
        sobrepeso = new javax.swing.JComboBox<>();
        alergias = new javax.swing.JComboBox<>();
        obesidad = new javax.swing.JComboBox<>();
        diabetes = new javax.swing.JComboBox<>();
        otros = new javax.swing.JTextField();
        estatus = new javax.swing.JComboBox<>();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cuadro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 375));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 400));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificacion.setBackground(new java.awt.Color(0, 0, 0));
        modificacion.setFont(new java.awt.Font("Corbel", 0, 36)); // NOI18N
        modificacion.setForeground(new java.awt.Color(0, 0, 153));
        modificacion.setText("PERSONAL");
        modificacion.setToolTipText("");
        jPanel1.add(modificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 50));

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel2.setText("Clave:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 115, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel3.setText("Sexo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 158, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel4.setText("Desnutrición:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 205, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel5.setText("Sobrepeso:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 251, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel6.setText("Alergias:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 251, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel7.setText("Obesidad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 208, -1, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel8.setText("Diabetes:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 161, -1, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel9.setText("Otros :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 161, -1, -1));

        jLabel10.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel10.setText("Estatus:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 208, -1, -1));

        clave.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                claveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                claveKeyTyped(evt);
            }
        });
        jPanel1.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 118, 100, -1));

        sexo.setBackground(new java.awt.Color(153, 102, 255));
        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "Masculino", "Femenino" }));
        sexo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sexo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                sexoItemStateChanged(evt);
            }
        });
        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 162, 80, 20));

        desnutricion.setBackground(new java.awt.Color(153, 102, 255));
        desnutricion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        desnutricion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        desnutricion.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                desnutricionItemStateChanged(evt);
            }
        });
        jPanel1.add(desnutricion, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 208, 80, -1));

        sobrepeso.setBackground(new java.awt.Color(153, 102, 255));
        sobrepeso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        sobrepeso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sobrepeso.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                sobrepesoItemStateChanged(evt);
            }
        });
        jPanel1.add(sobrepeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 254, 80, -1));

        alergias.setBackground(new java.awt.Color(153, 102, 255));
        alergias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        alergias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        alergias.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                alergiasItemStateChanged(evt);
            }
        });
        jPanel1.add(alergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 254, 80, -1));

        obesidad.setBackground(new java.awt.Color(153, 102, 255));
        obesidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        obesidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        obesidad.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                obesidadItemStateChanged(evt);
            }
        });
        jPanel1.add(obesidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 211, 80, -1));

        diabetes.setBackground(new java.awt.Color(153, 102, 255));
        diabetes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        diabetes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        diabetes.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                diabetesItemStateChanged(evt);
            }
        });
        jPanel1.add(diabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 164, 80, -1));

        otros.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                otrosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                otrosKeyTyped(evt);
            }
        });
        jPanel1.add(otros, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 164, 110, -1));

        estatus.setBackground(new java.awt.Color(153, 102, 255));
        estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "Base", "Temporal" }));
        estatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        estatus.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                estatusItemStateChanged(evt);
            }
        });
        jPanel1.add(estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 211, 100, -1));

        aceptar.setBackground(new java.awt.Color(86, 86, 252));
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 317, -1, -1));

        cancelar.setBackground(new java.awt.Color(86, 86, 252));
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 317, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 255));
        jLabel11.setText("MODIFICACIONES");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.angeru.images/Icons Ventana/Profesional.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.angeru.images/Paneles/PanelMorado.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.angeru.images/Paneles/Logo100.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        cuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.angeru.images/Imagen Ventana/Ventana850.png"))); // NOI18N
        jPanel1.add(cuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_claveKeyTyped
    {//GEN-HEADEREND:event_claveKeyTyped
        Validaciones.validaAlfanumerico(evt, 9, clave.getText());
    }//GEN-LAST:event_claveKeyTyped

    private void claveKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_claveKeyPressed
    {//GEN-HEADEREND:event_claveKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (ManipulacionProyecto.buscarCve(VtnPrincipal.arrDatos, clave.getText()) == -1)
            {
                Mensajes.error(this, "La clave no se encuentra registrada");
                cancelarActionPerformed(null);

            }else
            {
                if (VtnPrincipal.arrDatos[ManipulacionProyecto.buscarCve(VtnPrincipal.arrDatos, clave.getText())] instanceof Alumnos)
                {
                    Mensajes.error(this, "La clave no pertenece a Alumnos.");
                    cancelarActionPerformed(null);
                } else
                {
                    Validaciones.enterCadenaNoVacia(this, evt, clave, sexo);
                }
            }

        }
        Validaciones.enterCadenaNoVacia(this, evt, clave, sexo);
    }//GEN-LAST:event_claveKeyPressed

    private void sexoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_sexoItemStateChanged
    {//GEN-HEADEREND:event_sexoItemStateChanged
        CtrlInterfaz.cambia(desnutricion);
    }//GEN-LAST:event_sexoItemStateChanged

    private void desnutricionItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_desnutricionItemStateChanged
    {//GEN-HEADEREND:event_desnutricionItemStateChanged
        CtrlInterfaz.cambia(sobrepeso);
    }//GEN-LAST:event_desnutricionItemStateChanged

    private void sobrepesoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_sobrepesoItemStateChanged
    {//GEN-HEADEREND:event_sobrepesoItemStateChanged
        CtrlInterfaz.cambia(diabetes);
    }//GEN-LAST:event_sobrepesoItemStateChanged

    private void alergiasItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_alergiasItemStateChanged
    {//GEN-HEADEREND:event_alergiasItemStateChanged
        CtrlInterfaz.cambia(otros);
    }//GEN-LAST:event_alergiasItemStateChanged

    private void obesidadItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_obesidadItemStateChanged
    {//GEN-HEADEREND:event_obesidadItemStateChanged
        CtrlInterfaz.cambia(alergias);
    }//GEN-LAST:event_obesidadItemStateChanged

    private void diabetesItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_diabetesItemStateChanged
    {//GEN-HEADEREND:event_diabetesItemStateChanged
        CtrlInterfaz.cambia(obesidad);
    }//GEN-LAST:event_diabetesItemStateChanged

    private void otrosKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrosKeyTyped
    {//GEN-HEADEREND:event_otrosKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, otros.getText());
    }//GEN-LAST:event_otrosKeyTyped

    private void otrosKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrosKeyPressed
    {//GEN-HEADEREND:event_otrosKeyPressed
        if (!otros.getText().equals(""))
        {
            Validaciones.enter(this, evt, estatus, otros);
            Validaciones.enterCadenaNoVacia(this, evt, otros, estatus);
        } else
        {
            Validaciones.enter(this, evt, otros, otros);
            Validaciones.enterCadenaNoVacia(this, evt, otros, otros);

        }
    }//GEN-LAST:event_otrosKeyPressed

    private void estatusItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_estatusItemStateChanged
    {//GEN-HEADEREND:event_estatusItemStateChanged
        CtrlInterfaz.cambia(aceptar);
    }//GEN-LAST:event_estatusItemStateChanged

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        int pos;
        otros.setText(otros.getText().toUpperCase());
        try
        {

            if (ManipulacionProyecto.buscarCve(VtnPrincipal.arrDatos, clave.getText()) != -1)
            {

                if (sexo.getSelectedIndex() == 0 || desnutricion.getSelectedIndex() == 0 || sobrepeso.getSelectedIndex() == 0 || alergias.getSelectedIndex() == 0 || obesidad.getSelectedIndex() == 0 || diabetes.getSelectedIndex() == 0 || estatus.getSelectedIndex() == 0)
                {
                    Mensajes.error(this, "Porfavor, selecciona una opcion");

                } else
                {
                    if (clave.getText().equals("") || otros.getText().equals(""))
                    {
                        Mensajes.error(this, "La caja de texto esta vacia");
                    } else
                    {
                        pos = ManipulacionProyecto.buscarCve(VtnPrincipal.arrDatos, clave.getText());
                        VtnPrincipal.arrDatos = ManipulacionProyecto.modificarPersonal(VtnPrincipal.arrDatos, pos, clave.getText(), sexo.getSelectedIndex(), desnutricion.getSelectedIndex(), sobrepeso.getSelectedIndex(), alergias.getSelectedIndex(), obesidad.getSelectedIndex(), diabetes.getSelectedIndex(), otros.getText(), estatus.getSelectedIndex());
                        Mensajes.exito(this, "Datos modificados correctamente");
                        resetCombos();
                        cancelarActionPerformed(evt);
                    }

                }
            } else
            {
                Mensajes.error(this, "La clave no se encuentra registrada");
                cancelarActionPerformed(evt);
            }

        } catch (Exception e)
        {
            Mensajes.error(this, "Error..." + e.toString());
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarActionPerformed
    {//GEN-HEADEREND:event_cancelarActionPerformed
        CtrlInterfaz.limpia(clave, otros);
        resetCombos();
        CtrlInterfaz.habilita(false, sexo, desnutricion, sobrepeso, alergias, obesidad, diabetes, otros, estatus, aceptar);
        CtrlInterfaz.cambia(clave);
    }//GEN-LAST:event_cancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CtrlInterfaz.habilita(false, sexo, desnutricion, sobrepeso,alergias,obesidad,diabetes, otros, estatus, aceptar);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnMP().setVisible(true);
            }
        });
    }

    private void resetCombos()
    {
        sexo.setSelectedIndex(0);
        desnutricion.setSelectedIndex(0);
        sobrepeso.setSelectedIndex(0);
        alergias.setSelectedIndex(0);
        obesidad.setSelectedIndex(0);
        diabetes.setSelectedIndex(0);
        estatus.setSelectedIndex(0);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JComboBox<String> alergias;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField clave;
    private javax.swing.JLabel cuadro;
    private javax.swing.JComboBox<String> desnutricion;
    private javax.swing.JComboBox<String> diabetes;
    private javax.swing.JComboBox<String> estatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modificacion;
    private javax.swing.JComboBox<String> obesidad;
    private javax.swing.JTextField otros;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JComboBox<String> sobrepeso;
    // End of variables declaration//GEN-END:variables
}
