/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vtnsExtras;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import ventanaprincipal.VtnPrincipal;
import poo.Alumnos;
import poo.ManipulacionProyecto;
/**
 *
 * @author nolas
 */
public class VtnRA extends javax.swing.JFrame
{

    /**
     * Creates new form VtnRA
     */
    public VtnRA()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        clave = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        apP = new javax.swing.JTextField();
        apM = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox<>();
        desnutricion = new javax.swing.JComboBox<>();
        sobrepeso = new javax.swing.JComboBox<>();
        alergias = new javax.swing.JComboBox<>();
        obesidad = new javax.swing.JComboBox<>();
        diabetes = new javax.swing.JComboBox<>();
        viveCon = new javax.swing.JComboBox<>();
        carrera = new javax.swing.JComboBox<>();
        otros = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cuadro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("REGISTRO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel2.setText("Clave:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 139, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel4.setText("Apellido Paterno:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 139, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel5.setText("Apellido Materno:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 139, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel6.setText("Sexo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel7.setText("Desnutrición:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel8.setText("Sobrepeso:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel9.setText("Alergias:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 182, -1, -1));

        jLabel10.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel10.setText("Obesidad:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 226, -1, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel11.setText("Diabetes:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 278, -1, -1));

        jLabel12.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel12.setText("Otros:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 182, -1, -1));

        jLabel13.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel13.setText("Vive con:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 226, -1, -1));

        jLabel14.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel14.setText("Carrera: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        clave.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                claveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                claveKeyTyped(evt);
            }
        });
        jPanel1.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 100, -1));

        nom.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomKeyTyped(evt);
            }
        });
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 142, 100, -1));

        apP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                apPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                apPKeyTyped(evt);
            }
        });
        jPanel1.add(apP, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 142, 110, -1));

        apM.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                apMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                apMKeyTyped(evt);
            }
        });
        jPanel1.add(apM, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 142, 110, -1));

        sexo.setBackground(new java.awt.Color(153, 102, 255));
        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "Masculino", "Femenino" }));
        sexo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sexo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                sexoItemStateChanged(evt);
            }
        });
        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 80, -1));

        desnutricion.setBackground(new java.awt.Color(153, 102, 255));
        desnutricion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        desnutricion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        desnutricion.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                desnutricionItemStateChanged(evt);
            }
        });
        desnutricion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                desnutricionActionPerformed(evt);
            }
        });
        jPanel1.add(desnutricion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 80, -1));

        sobrepeso.setBackground(new java.awt.Color(153, 102, 255));
        sobrepeso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        sobrepeso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sobrepeso.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                sobrepesoItemStateChanged(evt);
            }
        });
        jPanel1.add(sobrepeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 80, -1));

        alergias.setBackground(new java.awt.Color(153, 102, 255));
        alergias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        alergias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        alergias.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                alergiasItemStateChanged(evt);
            }
        });
        jPanel1.add(alergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 185, 80, -1));

        obesidad.setBackground(new java.awt.Color(153, 102, 255));
        obesidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        obesidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        obesidad.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                obesidadItemStateChanged(evt);
            }
        });
        jPanel1.add(obesidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 229, 80, -1));

        diabetes.setBackground(new java.awt.Color(153, 102, 255));
        diabetes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "No", "Si" }));
        diabetes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        diabetes.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                diabetesItemStateChanged(evt);
            }
        });
        jPanel1.add(diabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 281, 80, -1));

        viveCon.setBackground(new java.awt.Color(153, 102, 255));
        viveCon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "Mamá y Papá", "Solo Mamá", "Solo Papá", "Otros" }));
        viveCon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        viveCon.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                viveConItemStateChanged(evt);
            }
        });
        jPanel1.add(viveCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 229, -1, -1));

        carrera.setBackground(new java.awt.Color(153, 102, 255));
        carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la opcion", "Ing. Electromecánica", "Ing. Electrónica", "Ing. Gestión Empresarial", "Ing. Industrial", "Ing. Logística", "Ing. Mecatrónica", "Ing. Química", "Ing. Sistemas Computacionales", "Ing. en TIC'S" }));
        carrera.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        carrera.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                carreraItemStateChanged(evt);
            }
        });
        jPanel1.add(carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 281, 144, -1));

        otros.setText("NINGUNO");
        otros.setPreferredSize(new java.awt.Dimension(64, 32));
        otros.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                otrosActionPerformed(evt);
            }
        });
        otros.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                otrosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                otrosKeyTyped(evt);
            }
        });
        jPanel1.add(otros, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 185, 144, 23));

        aceptar.setBackground(new java.awt.Color(86, 86, 252));
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 331, -1, -1));

        cancelar.setBackground(new java.awt.Color(86, 86, 252));
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 331, -1, -1));

        jLabel16.setFont(new java.awt.Font("Corbel", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("ALUMNOS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.angeru.images/Icons Ventana/Alumn.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 60, 70));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.angeru.images/Paneles/PanelMorado.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.angeru.images/Paneles/Logo100.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        cuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.angeru.images/Imagen Ventana/Ventana850.png"))); // NOI18N
        jPanel1.add(cuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 830, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_claveKeyTyped
    {//GEN-HEADEREND:event_claveKeyTyped
        Validaciones.validaAlfanumerico(evt, 9, clave.getText());
    }//GEN-LAST:event_claveKeyTyped

    private void claveKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_claveKeyPressed
    {//GEN-HEADEREND:event_claveKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (ManipulacionProyecto.buscarCve(VtnPrincipal.arrDatos, clave.getText()) != -1)
            {
                Mensajes.error(this, "La clave ya se encuentra registrada");
                cancelarActionPerformed(null);
            }

        }
        Validaciones.enterCadenaNoVacia(this, evt, clave, nom);
    }//GEN-LAST:event_claveKeyPressed

    private void nomKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyTyped
    {//GEN-HEADEREND:event_nomKeyTyped
        Validaciones.validaAlfabeticos(evt, 15, nom.getText());
    }//GEN-LAST:event_nomKeyTyped

    private void nomKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyPressed
    {//GEN-HEADEREND:event_nomKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, nom, apP);
    }//GEN-LAST:event_nomKeyPressed

    private void apPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apPKeyTyped
    {//GEN-HEADEREND:event_apPKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, apP.getText());
    }//GEN-LAST:event_apPKeyTyped

    private void apPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apPKeyPressed
    {//GEN-HEADEREND:event_apPKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, apP, apM);
    }//GEN-LAST:event_apPKeyPressed

    private void apMKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apMKeyTyped
    {//GEN-HEADEREND:event_apMKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, apM.getText());
    }//GEN-LAST:event_apMKeyTyped

    private void apMKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apMKeyPressed
    {//GEN-HEADEREND:event_apMKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, apM, sexo);
    }//GEN-LAST:event_apMKeyPressed

    private void sexoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_sexoItemStateChanged
    {//GEN-HEADEREND:event_sexoItemStateChanged
        CtrlInterfaz.cambia(desnutricion);
    }//GEN-LAST:event_sexoItemStateChanged

    private void desnutricionItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_desnutricionItemStateChanged
    {//GEN-HEADEREND:event_desnutricionItemStateChanged
        CtrlInterfaz.cambia(sobrepeso);
    }//GEN-LAST:event_desnutricionItemStateChanged

    private void sobrepesoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_sobrepesoItemStateChanged
    {//GEN-HEADEREND:event_sobrepesoItemStateChanged
        CtrlInterfaz.cambia(alergias);
    }//GEN-LAST:event_sobrepesoItemStateChanged

    private void alergiasItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_alergiasItemStateChanged
    {//GEN-HEADEREND:event_alergiasItemStateChanged
        CtrlInterfaz.cambia(obesidad);
    }//GEN-LAST:event_alergiasItemStateChanged

    private void obesidadItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_obesidadItemStateChanged
    {//GEN-HEADEREND:event_obesidadItemStateChanged
        CtrlInterfaz.cambia(diabetes);
    }//GEN-LAST:event_obesidadItemStateChanged

    private void diabetesItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_diabetesItemStateChanged
    {//GEN-HEADEREND:event_diabetesItemStateChanged
        CtrlInterfaz.cambia(otros);
    }//GEN-LAST:event_diabetesItemStateChanged

    private void otrosKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrosKeyTyped
    {//GEN-HEADEREND:event_otrosKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, otros.getText());
    }//GEN-LAST:event_otrosKeyTyped

    private void otrosKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_otrosKeyPressed
    {//GEN-HEADEREND:event_otrosKeyPressed
        if (!otros.getText().equals(""))
        {
            Validaciones.enter(this, evt, viveCon, otros);
            Validaciones.enterCadenaNoVacia(this, evt, otros, viveCon);
        } else
        {
            Validaciones.enter(this, evt, otros, otros);
            Validaciones.enterCadenaNoVacia(this, evt, otros, otros);
        
        }
    }//GEN-LAST:event_otrosKeyPressed

    private void viveConItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_viveConItemStateChanged
    {//GEN-HEADEREND:event_viveConItemStateChanged
        CtrlInterfaz.cambia(carrera);
    }//GEN-LAST:event_viveConItemStateChanged

    private void carreraItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_carreraItemStateChanged
    {//GEN-HEADEREND:event_carreraItemStateChanged
        CtrlInterfaz.cambia(aceptar);
    }//GEN-LAST:event_carreraItemStateChanged

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        otros.setText(otros.getText().toUpperCase());
        try
        {

            if (ManipulacionProyecto.buscarCve(VtnPrincipal.arrDatos, clave.getText()) == -1)
            {

                if (sexo.getSelectedIndex() == 0 || desnutricion.getSelectedIndex() == 0 || sobrepeso.getSelectedIndex() == 0 || alergias.getSelectedIndex() == 0 || obesidad.getSelectedIndex() == 0 || diabetes.getSelectedIndex() == 0 || viveCon.getSelectedIndex() == 0 || carrera.getSelectedIndex() == 0)
                {
                    Mensajes.error(this, "Porfavor, selecciona una opcion");

                } else
                {
                    if (clave.getText().equals("") || nom.getText().equals("") || apP.getText().equals("") || apM.getText().equals("") || otros.getText().equals(""))
                    {
                        Mensajes.error(this, "La caja de texto esta vacia");
                    } else
                    {
                        VtnPrincipal.arrDatos = ManipulacionProyecto.agregarAlumno(VtnPrincipal.arrDatos, 1, true, asignarDatos(null, viveCon.getSelectedIndex(), carrera.getSelectedIndex(), clave.getText(), nom.getText(), apP.getText(), apM.getText(), sexo.getSelectedIndex(), desnutricion.getSelectedIndex(), sobrepeso.getSelectedIndex(), alergias.getSelectedIndex(), obesidad.getSelectedIndex(), diabetes.getSelectedIndex(), otros.getText()));
                        VtnPrincipal.matH = ManipulacionProyecto.agregarfila(VtnPrincipal.matH);
                        Mensajes.exito(this, "Datos registrados correctamente");
                        resetCombos();
                        cancelarActionPerformed(evt);

                    }

                }
            } else
            {
                Mensajes.error(this, "La clave ya se encuentra registrada");
                cancelarActionPerformed(evt);
            }

        } catch (Exception e)
        {
            Mensajes.error(this, "Error..." + e.toString());
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarActionPerformed
    {//GEN-HEADEREND:event_cancelarActionPerformed
        CtrlInterfaz.limpia(clave, nom, apP, apM, otros);
        otros.setText("NINGUNO");
        resetCombos();
        CtrlInterfaz.habilita(false, nom, apP, apM, otros, sexo, desnutricion, sobrepeso, alergias, obesidad, diabetes, otros, viveCon, carrera, aceptar);
        CtrlInterfaz.cambia(clave);
    }//GEN-LAST:event_cancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CtrlInterfaz.habilita(false, nom, apP, apM, otros, sexo, desnutricion, sobrepeso, alergias, obesidad, diabetes, otros, viveCon, carrera, aceptar);
    }//GEN-LAST:event_formWindowOpened

    private void otrosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_otrosActionPerformed
    {//GEN-HEADEREND:event_otrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otrosActionPerformed

    private void desnutricionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_desnutricionActionPerformed
    {//GEN-HEADEREND:event_desnutricionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desnutricionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnRA().setVisible(true);
            }
        });
    }

    private void resetCombos()
    {
        sexo.setSelectedIndex(0);
        desnutricion.setSelectedIndex(0);
        sobrepeso.setSelectedIndex(0);
        alergias.setSelectedIndex(0);
        obesidad.setSelectedIndex(0);
        diabetes.setSelectedIndex(0);
        viveCon.setSelectedIndex(0);
        carrera.setSelectedIndex(0);

    }

    private Alumnos asignarDatos(java.awt.event.ActionEvent evt, int viveCon, int carrera, String clave, String nombre, String apP, String apM, int sex, int des, int sobre, int aler, int obes, int diab, String otros)
    {
        char sexo = ' ';
        boolean desnutricion = false;
        boolean sobrepeso = false;
        boolean alergias = false;
        boolean obesidad = false;
        boolean diabetes = false;

        switch (sex)
        {
            case 1:
                sexo = 'M';
                break;
            case 2:
                sexo = 'F';
                break;
        }

        switch (des)
        {
            case 1:
                desnutricion = false;
                break;
            case 2:
                desnutricion = true;
                break;
        }
        switch (sobre)
        {
            case 1:
                sobrepeso = false;
                break;
            case 2:
                sobrepeso = true;
                break;
        }
        switch (aler)
        {
            case 1:
                alergias = false;
                break;
            case 2:
                alergias = true;
                break;
        }
        switch (obes)
        {
            case 1:
                obesidad = false;
                break;
            case 2:
                obesidad = true;
                break;
        }
        switch (diab)
        {
            case 1:
                diabetes = false;
                break;
            case 2:
                diabetes = true;
                break;
        }
        Alumnos obj = new Alumnos(viveCon, carrera, clave, nombre, apP, apM, sexo, desnutricion, sobrepeso, alergias, obesidad, diabetes, otros);
        return obj;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JComboBox<String> alergias;
    private javax.swing.JTextField apM;
    private javax.swing.JTextField apP;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox<String> carrera;
    private javax.swing.JTextField clave;
    private javax.swing.JLabel cuadro;
    private javax.swing.JComboBox<String> desnutricion;
    private javax.swing.JComboBox<String> diabetes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nom;
    private javax.swing.JComboBox<String> obesidad;
    private javax.swing.JTextField otros;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JComboBox<String> sobrepeso;
    private javax.swing.JComboBox<String> viveCon;
    // End of variables declaration//GEN-END:variables
}
